### ISSUE TITLE
ESM mandatory file extensions

### ISSUE THREAD

**Issue by aureooms** [wessberg/cjstoesm#11]
Does this tool handle replacement of old require/import syntax with [the new one that requires file extensions](https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_mandatory_file_extensions)?

**Comment by wessberg** [comment]
Hey there,

Sorry for the late reply.

Currently, the CommonJS module specifiers are preserved. `cjstoesm` is strictly performing a syntax transformation here.
As far as defaults go, I think that yes, it would make sense to switch over to automatically adding extensions to the module specifiers to align with how ESM works in both browser and Node going forward, and then provide an option for preserving the extension-less module specifiers such as TypeScript- and CommonJS users are used to. I'm going to mark this as a feature request and see if I can find the time to implement it.

**Comment by wessberg** [comment]
Hey again,

I went ahead and implemented this and released it as part of [v1.0.0](https://github.com/wessberg/cjstoesm/releases/tag/v1.0.0). It is of course a breaking change, so I had to bump the SemVer major version.
