### ISSUE TITLE
NPM package does not export Typescript transformer

### ISSUE THREAD

**Issue by capricorn86** [wessberg/cjstoesm#12]
Hi!

Thanks for providing with what seem to be a great tool!

I have been trying to use your Typescript transformer, but without success. It seems like the NPM package doesn't export it.

**My code:**
```javascript
import {cjsToEsmTransformerFactory} from 'cjstoesm';

export default class TypescriptTranspiler {
	public transpileModule(
		code: string,
		filepath: string,
	): string {
		const results = TypeScript.transpileModule(code, {
			compilerOptions: COMPILER_OPTIONS,
			fileName: filepath,
			transformers: {
                                before: [cjsToEsmTransformerFactory()]
                            }
		});
                return results.outputText.toString();
	}
}
```

**Code in cjstoesm/dist/lib/esm/index.js:**
```javascript
import 'typescript';
import 'resolve';
import 'path';
import 'slash';
import '@wessberg/stringutil';
import 'reserved-words';
import 'fs';
import 'util';
import 'glob';
import 'chalk';
//# sourceMappingURL=index.js.map
```

The exports seems to be missing and I can't find the code for "cjsToEsmTransformerFactory" in the package.

**Comment by wessberg** [comment]
Whoops, sorry about that, this is a regression in v1.0.0 that was released yesterday. A [new version has been published to npm](https://github.com/wessberg/cjstoesm/releases/tag/v1.0.1) that fixes this. Thanks for noticing this so quickly!

**Comment by capricorn86** [comment]
That was quick! Thank you :slightly_smiling_face:
