### ISSUE TITLE
[BUG] Cannot find module 'typescript'

### ISSUE THREAD

**Issue by gilles-yvetot** [wessberg/cjstoesm#13]
I just installed your package: `npm i cjstoesm -g` then  run `cjstoesm` in the console and got this error:

```
Error: Cannot find module 'typescript'
Require stack:
- /usr/local/lib/node_modules/cjstoesm/dist/cli/index.js
- /usr/local/lib/node_modules/cjstoesm/bin/cjstoesm
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cjstoesm/dist/cli/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/cjstoesm/dist/cli/index.js',
    '/usr/local/lib/node_modules/cjstoesm/bin/cjstoesm'
  ]
}
```

**Comment by gilles-yvetot** [comment]
I just noted that you listed typescript as part of the deps

**Comment by wessberg** [comment]
Yes, typescript is a peer dependency and usage is documented [here](https://github.com/wessberg/cjstoesm#install)

**Comment by KaKi87** [comment]
Hello,

`require`d dependencies should be listed as `dependencies` and not as `peerDependencies` *([source](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies))*.

Please fix it accordingly.

Thanks

**Comment by KaKi87** [comment]
> The reason why libraries may declare a non-optional dependency as a peer dependency and _not_ as a hard dependency is to allow consumers to use whatever version of the related package _they_ want.

Actually, the fact that your project would depend on a specific version of a package doesn't prevent the user from adding a different version of that package as a direct dependency.

**Comment by wessberg** [comment]
Hi again.

Again, I want to reiterate that peer dependencies are not _optional_ dependencies, as your comment seems to imply. You can, however, annotate them as such with `peerDependenciesMeta` as a library author if your package declares dependencies that the consuming user may only optionally install. TypeScript, however, is a required peer dependency of `cjstoesm`.

Please consult the official documentation or any of the [existing great articles](https://nodejs.org/es/blog/npm/peer-dependencies/) you can find online explaining when you may want to use peer dependencies, and when not to.
