### ISSUE TITLE
Cannot run with npx

### ISSUE THREAD

**Issue by thernstig** [wessberg/cjstoesm#14]
Tried to run it according to the docs, but got a failure for typescript:

```sh
npx -p typescript cjstoesm "server/util/**/*.*" server/util/esm/
npx: installed 1 in 1.844s
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
- /home/userA/code/proj/node_modules/cjstoesm/dist/cli/index.js
- /home/userA/code/proj/node_modules/cjstoesm/bin/cjstoesm
```

**Comment by wessberg** [comment]
Hey there,
`typescript` is a peer dependency of `cjstoesm`, so you can do one of the following:

a) Install `typescript` globally before running the command with `npm install -g typescript`. Now you can just do `npx cjstoesm`.

or

b) Run the somewhat bloated `npx -p typescript -p cjstoesm cjstoesm "server/util/**/*.*" server/util/esm/` command instead. Unfortunately, it would seem this is how `npx` works. I'll update the documentation as soon as possible with this.

**Comment by thernstig** [comment]
Great, it was the fact that the docs did not work out of the box, but if you amend it with the last example I hope it will :)
