### ISSUE TITLE
Support for direct in-place replacement?

### ISSUE THREAD

**Issue by nopeless** [wessberg/cjstoesm#24]
~~cjstoesm src/**/*.* src creates another src directory in src `src/src`~~

doing `ejstoesm **/*.* .` in `/src` directory does not work

or please add an option to copy other files such as `.yml`, `.json` files in the directory as well. I think I have to manually move those non js files for now

**Comment by wessberg** [comment]
Hey there. Thanks for the suggestion. I agree, and I'm looking into this.

**Comment by wessberg** [comment]
This has been fixed [in this commit](https://github.com/wessberg/cjstoesm/commit/78592d0d33e1116b6cc2ff81dd010a3f1b63254c).

The default behavior from the next major version of `cjstoesm` is in fact to allow overwriting files in-place. An output directory can be optionally provided as the second argument to `cjstoesm` in case the files should be emitted to a different directory. This is of course a breaking change, so expect to see a bump to the major version soon.
