### ISSUE TITLE
import is needless for the dead code

### ISSUE THREAD

**Issue by creamidea** [wessberg/cjstoesm#7]
I have the code below
```js
require('./c');

if (true) {
  require('./a');
} else {
  require('./b');
}

function A () {
  console.log('hhhh');
}

module.exports = A;
```

and I use commond `cjstoesm a.js esm` to transform. I got the result below

![image](https://user-images.githubusercontent.com/1274730/99785964-decc9d00-2b58-11eb-8e41-fdce0828f04a.png)

would you please to support this feature?

**Comment by creamidea** [comment]
Or is this the duty of the terser ?

**Comment by wessberg** [comment]
This is already answered in the FAQ [here](https://github.com/wessberg/cjstoesm/blob/master/README.md#faq). As far your question about dead code removal, then no, `cjstoesm` simply converts CJS-based files into equivalent ESM (if possible).
