### ISSUE TITLE
Do not replicate the whole directory structure in the output

### ISSUE THREAD

**Issue by manuel-mauky** [wessberg/cjstoesm#9]
In a npm project I'm trying to transform a library in node_modules from the CLI.
When I execute a command like this: `cjstoesm node_modules/@something/some_library_name/dist/index.js target` the transformed output files are stored in `target/node_modules/@something/some_library_name/dist` where I would expect to have the transformed files directly in `target`. 
The CLI is replicating the whole folder structure in the target dir. 
This makes it a bit complicated to use the command from a top level directory. 
I think this behaviour would be fine if I would run the command with a nonspecific glob like `cjstoesm **/*.js target` because in this case of cause the tool would run into conflicting files. 
Wouldn't it be better to start replicating the folder structure only at the point were the glob has it's wildcards, for example `cjstoesm node_modules/@something/**/*.js` should replicate the folders below `@something/`?

**Comment by wessberg** [comment]
Hi Manuel,

I definitely agree. I'll look into how other similar tools are generating output directory structures and will consider your suggestion regarding using the first wildcard as the root.

**Comment by anoblet** [comment]
Interested in this as well.

**Comment by wessberg** [comment]
This has been fixed [in this commit](https://github.com/wessberg/cjstoesm/commit/78592d0d33e1116b6cc2ff81dd010a3f1b63254c) and will be part of the next major release.
